services:
  redis:
    image: 'redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    restart: unless-stopped
    build:
      context: .
    image: "ipification_showcase"
    environment:
      PORT: 8080
      REDIS_URL: redis://redis
    ports:
      - 3001:8080
    links:
      - redis
    depends_on:
      - redis
