services:
  app:
    restart: unless-stopped
    build:
      context: .
    image: "ipification_showcase"
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    volumes:
      - ./config/default.json.docker:/usr/app/config/default.json
