server {
    listen       8080;
    server_name  ipification.local;
    root         project_path/public;

    location ~ \.(html|json|css|ttf|woff|woff2|js|css.map)$ {
      root project_path/public;
      access_log off;
      proxy_pass http://localhost:3000;
    }

    location /webapp/ {
        rewrite ^/webapp/(.*)$ /$1 break;
        proxy_pass http://localhost:3000/;
    }


}



