const QR_CODE_SUFFIX = '-qrcode';

const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500
};

const ERROR_MESSAGES = {
  CLIENT_NOT_FOUND: 'Client not found'
};

const MAX_RETRY_ATTEMPTS = 4;
const RETRY_DELAY_MS = 1000;

module.exports = {
  QR_CODE_SUFFIX,
  HTTP_STATUS,
  ERROR_MESSAGES,
  MAX_RETRY_ATTEMPTS,
  RETRY_DELAY_MS
};
